# Generated by Django 5.2.8 on 2025-11-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'managed': True},
        ),
    ]
